travis:
  secure:
    BINSTAR_TOKEN: lVxImlUCKk35QjuPGiBViUxJv5CyKeA0ZbgerKm0yu9z3e/OfDULnqewt5slS4WpFPNJRd8HXTrSM58B1LeVk6Z4bFpNkDcxle8Fw7mV0VBn7+MKxP3ZESpU3cO8oAURwA9BneDreCz7C6h+zxCog2T0supkIgbz1P36nRG0NRme2RKQgashDnajdrKFqAvk9jkj0lY/MP9ko0JQJnotKGUQhMgE8Palrrnf50mRxMYVMedJ0gyVypAQeIDFNkoQ0H+jwygrbL1ezztENTITVmULYUKkSKXdWto9PF80+9qHv0IEorLRbcufGx2S5lip6eZrc+ZPG7vr0UVOQRJBOte7Ghsmb++qvL8zXP5Vx40VzWW3o4FFwtu2jqblq51t9XFmjION41foogaK1f1kjel7+cwMtDd2aeZGnhk8nVF0j70gradK1uC5844pVFT1bTNw8jnimwtJTHfgHhATuplhmRCdRS5siUPGWUpfMZj6aolUpRZxmBtp7CZtW52GHER5psReiCttJbGPzQFkPNZSqQOghKgH5ZzJbnqcWqMZ6H4mNWgCOjnBVoWvMJs58HCUm8LA9fKbfY5Gxm6GRG8s3ZuzhHV36C2DW6iJVJRbwHBBi0i6+UxVe/zm8bcTkZnxYk/B2kK5opCfH2mMWcewXwgMwMB6aXqUaUUbkKo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
